[package]
name = "omf"
version = "0.1.0-alpha.2"
description = "File reader and writer for Open Mining Format."
authors = ["Tim Evans <tim.evans@seequent.com>"]
license = "MIT"
edition = "2021"
publish = true
exclude = ["/.github", "/.vscode"]

[dependencies]
bytes = { workspace = true, optional = true }
chrono.workspace = true
flate2.workspace = true
image = { workspace = true, optional = true }
parquet = { workspace = true, optional = true }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip.workspace = true

[dev-dependencies]
bytes.workspace = true
regex.workspace = true

[features]
default = ["image", "parquet", "omf1"]
image = ["dep:image"]
parquet = ["dep:parquet", "dep:bytes"]
omf1 = ["parquet"]

[workspace]
members = ["omf-c"]

[workspace.dependencies]
bytes = "1.4.0"
cbindgen = { version = "0.24.5", default-features = false }
chrono = { version = "0.4.30", default-features = false, features = ["serde"] }
flate2 = "1.0.27"
image = { version = "0.24.7", default-features = false, features = ["png", "jpeg"]  }
parquet = { version = "46.0.0", default-features = false, features = ["flate2"] }
regex = "1.9.3"
schemars = { version = "0.8.12", features = ["chrono"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["float_roundtrip"] }
thiserror = "1.0.47"
zip = { version = "0.6.6", default-features = false }
