name: Docs

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build docs
        run: |
          cd docs
          sh build.sh

      - name: Fix permissions
        run: |
          chmod -c -R +rX "./site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Store artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/

  deploy:
    needs: docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v2
